# Generated by Django 3.1.3 on 2020-11-23 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='peritem',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='orders',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='orders',
            name='totalprice',
            field=models.IntegerField(default=0),
        ),
    ]
