# Generated by Django 3.1.3 on 2020-12-05 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0006_customer_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Out Of delivery', 'Out Of delivery'), ('delivered', 'delivered')], default='Pending', max_length=200, null=True),
        ),
    ]
